spring.application.name=BackendVPN
spring.datasource.url=jdbc:mysql://localhost:3306/vpndb
spring.datasource.username=root
spring.datasource.password=Rama9999@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



server.port=8080
