spring.application.name=BackendVPN
spring.datasource.url=jdbc:mysql://localhost:3306/vpndb
spring.datasource.username=root
spring.datasource.password=Rama9999@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=08c54feabc1b55bc16a23ec8c5757130ee1443d9094491b469c525359dcf0ceb
jwt.expiration=86400000  

razorpay.key.id=rzp_test_09PJY0SdHcAB2O
razorpay.key.secret=bIzBbEfRLCNdhOdinXy2oiN2

server.port=8080
