spring.application.name=BackendVPN
server.port=8080

# Correct MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vpndb
spring.datasource.username=root
spring.datasource.password=Rama9999@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
